### ISSUE TITLE
Fails to build: Xcode 11 Beta 2

### ISSUE THREAD

**Issue by ladvoc** [artemnovichkov/SwiftUI-by-Examples#1]
Thank you for putting together this fantastic resource!

Unfortunately, I get a few build errors when trying to build and run in Xcode 11 beta 2:
- [ButtonsView.swift line 17](https://github.com/artemnovichkov/SwiftUI-by-Examples/blob/master/SwiftUI%20by%20Examples/SwiftUI%20by%20Examples/ButtonsView.swift#L17): "'String' is not convertible to 'Any'"
- [ListView.swift line 30](https://github.com/artemnovichkov/SwiftUI-by-Examples/blob/master/SwiftUI%20by%20Examples/SwiftUI%20by%20Examples/VideoListView.swift#L30): "Unable to infer complex closure return type; add explicit type to disambiguate"

**Comment by artemnovichkov** [comment]
Hi, @jacobgelman! Thanks for the warm words and the issue! I'll check it in the new beta.

**Comment by artemnovichkov** [comment]
The issues were related to new `PresentationButton` initializer. I've pushed my changes. Could you please check it?

**Comment by ladvoc** [comment]
That fixed it! Thank you!

**Comment by artemnovichkov** [comment]
You're welcome, man!
